'use strict'

// Covers adapters/lib/deprecated.sh — the pruning of instruction files belonging
// to tools dropped in v3.0.0 (Windsurf/Copilot/Gemini/Antigravity).
//
// This deletes files inside a user's project, so the marker check is the safety
// property that matters most: a hand-written .windsurfrules must survive.

const test = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')

const REPO = path.join(__dirname, '..')
const DEPRECATED_SH = path.join(REPO, 'adapters', 'lib', 'deprecated.sh')

const GENERATED_HEADER =
  '# 100x Dev — Modules\n# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n\nbody\n'

function makeProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), '100x-prune-'))
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel)
    fs.mkdirSync(path.dirname(full), { recursive: true })
    fs.writeFileSync(full, content)
  }
  return dir
}

// Sources the helper and runs it, returning { count, stdout }.
function prune(projectDir) {
  const stdout = execFileSync(
    'bash',
    ['-c', `source "${DEPRECATED_SH}"; prune_deprecated_artifacts "${projectDir}"; echo "COUNT=$PRUNED_COUNT"`],
    { encoding: 'utf8' },
  )
  return { count: Number(/COUNT=(\d+)/.exec(stdout)[1]), stdout }
}

test('prunes every generated artifact from the dropped tools', () => {
  const dir = makeProject({
    '.windsurfrules': GENERATED_HEADER,
    'GEMINI.md': GENERATED_HEADER,
    'ANTIGRAVITY.md': GENERATED_HEADER,
    '.github/copilot-instructions.md': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 4, 'removed all four generated artifacts')
  for (const f of ['.windsurfrules', 'GEMINI.md', 'ANTIGRAVITY.md', '.github/copilot-instructions.md']) {
    assert.ok(!fs.existsSync(path.join(dir, f)), `${f} should be gone`)
  }
})

test('never deletes a file it did not generate', () => {
  const handWritten = '# my own Windsurf rules\nkeep me\n'
  const dir = makeProject({
    '.windsurfrules': handWritten,
    'GEMINI.md': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 1, 'only the generated file counted')
  assert.equal(
    fs.readFileSync(path.join(dir, '.windsurfrules'), 'utf8'),
    handWritten,
    'hand-written file preserved byte-for-byte',
  )
  assert.ok(!fs.existsSync(path.join(dir, 'GEMINI.md')), 'generated file removed')
})

test('leaves supported tools untouched', () => {
  const dir = makeProject({
    'CLAUDE.md': '# project instructions\n',
    'AGENTS.md': GENERATED_HEADER,
    '.cursor/rules/gate.mdc': '---\ndescription: x\n---\n',
    '.windsurfrules': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 1, 'only the deprecated artifact was pruned')
  assert.ok(fs.existsSync(path.join(dir, 'CLAUDE.md')), 'Claude Code file kept')
  assert.ok(fs.existsSync(path.join(dir, 'AGENTS.md')), 'Codex file kept even though it carries our header')
  assert.ok(fs.existsSync(path.join(dir, '.cursor', 'rules', 'gate.mdc')), 'Cursor rules kept')
})

test('is a no-op on a project with nothing to prune', () => {
  const dir = makeProject({ 'CLAUDE.md': '# nothing to do here\n' })

  const { count } = prune(dir)

  assert.equal(count, 0)
  assert.ok(fs.existsSync(path.join(dir, 'CLAUDE.md')))
})
