'use strict'

// Covers adapters/lib/deprecated.sh — the pruning of instruction files belonging
// to tools dropped in v3.0.0 (Windsurf/Copilot/Gemini/Antigravity).
//
// This deletes files inside a user's project, so the marker check is the safety
// property that matters most: a hand-written .windsurfrules must survive.

const test = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')

const REPO = path.join(__dirname, '..')
const DEPRECATED_SH = path.join(REPO, 'adapters', 'lib', 'deprecated.sh')

const GENERATED_HEADER =
  '# 100x Dev — Modules\n# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n\nbody\n'

function makeProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), '100x-prune-'))
  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel)
    fs.mkdirSync(path.dirname(full), { recursive: true })
    fs.writeFileSync(full, content)
  }
  return dir
}

// Sources the helper and runs it, returning { count, stdout }.
function prune(projectDir) {
  const stdout = execFileSync(
    'bash',
    ['-c', `source "${DEPRECATED_SH}"; prune_deprecated_artifacts "${projectDir}"; echo "COUNT=$PRUNED_COUNT"`],
    { encoding: 'utf8' },
  )
  return { count: Number(/COUNT=(\d+)/.exec(stdout)[1]), stdout }
}

test('prunes every generated artifact from the dropped tools', () => {
  const dir = makeProject({
    '.windsurfrules': GENERATED_HEADER,
    'GEMINI.md': GENERATED_HEADER,
    'ANTIGRAVITY.md': GENERATED_HEADER,
    '.github/copilot-instructions.md': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 4, 'removed all four generated artifacts')
  for (const f of ['.windsurfrules', 'GEMINI.md', 'ANTIGRAVITY.md', '.github/copilot-instructions.md']) {
    assert.ok(!fs.existsSync(path.join(dir, f)), `${f} should be gone`)
  }
})

test('never deletes a file it did not generate', () => {
  const handWritten = '# my own Windsurf rules\nkeep me\n'
  const dir = makeProject({
    '.windsurfrules': handWritten,
    'GEMINI.md': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 1, 'only the generated file counted')
  assert.equal(
    fs.readFileSync(path.join(dir, '.windsurfrules'), 'utf8'),
    handWritten,
    'hand-written file preserved byte-for-byte',
  )
  assert.ok(!fs.existsSync(path.join(dir, 'GEMINI.md')), 'generated file removed')
})

test('leaves supported tools untouched', () => {
  const dir = makeProject({
    'CLAUDE.md': '# project instructions\n',
    'AGENTS.md': GENERATED_HEADER,
    '.cursor/rules/gate.mdc': '---\ndescription: x\n---\n',
    '.windsurfrules': GENERATED_HEADER,
  })

  const { count } = prune(dir)

  assert.equal(count, 1, 'only the deprecated artifact was pruned')
  assert.ok(fs.existsSync(path.join(dir, 'CLAUDE.md')), 'Claude Code file kept')
  assert.ok(fs.existsSync(path.join(dir, 'AGENTS.md')), 'Codex file kept even though it carries our header')
  assert.ok(fs.existsSync(path.join(dir, '.cursor', 'rules', 'gate.mdc')), 'Cursor rules kept')
})

test('is a no-op on a project with nothing to prune', () => {
  const dir = makeProject({ 'CLAUDE.md': '# nothing to do here\n' })

  const { count } = prune(dir)

  assert.equal(count, 0)
  assert.ok(fs.existsSync(path.join(dir, 'CLAUDE.md')))
})

test('backs every removed file up before deleting it', () => {
  const dir = makeProject({ '.windsurfrules': GENERATED_HEADER })
  const home = fs.mkdtempSync(path.join(os.tmpdir(), '100x-home-'))

  execFileSync('bash', ['-c',
    `export HOME="${home}"; source "${DEPRECATED_SH}"; prune_deprecated_artifacts "${dir}"`,
  ], { encoding: 'utf8' })

  assert.ok(!fs.existsSync(path.join(dir, '.windsurfrules')), 'original removed')
  // Deletion must never be unrecoverable, even for uncommitted local edits.
  const backups = execFileSync('bash', ['-c',
    `find "${home}/.100xprism/removed-artifacts" -name .windsurfrules -type f | head -1`,
  ], { encoding: 'utf8' }).trim()
  assert.ok(backups, 'a backup copy exists under ~/.100xprism/removed-artifacts')
  assert.equal(fs.readFileSync(backups, 'utf8'), GENERATED_HEADER, 'backup is byte-identical')
})

test('refuses to delete through a symlink that escapes the project', () => {
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), '100x-outside-'))
  fs.writeFileSync(path.join(outside, 'copilot-instructions.md'), GENERATED_HEADER)

  const dir = makeProject({ 'CLAUDE.md': '# x\n' })
  fs.symlinkSync(outside, path.join(dir, '.github'), 'dir')

  const { count } = prune(dir)

  assert.equal(count, 0, 'nothing pruned through the escaping symlink')
  assert.ok(
    fs.existsSync(path.join(outside, 'copilot-instructions.md')),
    'a shared config directory outside the project must survive',
  )
})

test('ignores the marker when it appears below the header region', () => {
  // A user file that merely mentions us deep in its body is not ours to delete.
  const body = '# my rules\n' + 'filler\n'.repeat(20) + 'see: Generated by 100xprism\n'
  const dir = makeProject({ 'GEMINI.md': body })

  const { count } = prune(dir)

  assert.equal(count, 0, 'marker outside the header window does not authorise deletion')
  assert.equal(fs.readFileSync(path.join(dir, 'GEMINI.md'), 'utf8'), body)
})
