'use strict'

// `100xprism update --check-only` (and `100xprism check`) is a notify-only
// contract, commonly wired into cron. Reconciliation DELETES deprecated
// artifacts from the user's repositories, so it must never run under that flag.
//
// Regression: when the repo was already current, the reconcile call was placed
// ahead of the check-only guard, turning a read-only status command into one
// that silently deleted files across every tracked project.
//
// The buggy branch is only reachable when HEAD === origin/main, so these tests
// build a real clone rather than running against the working checkout — where
// HEAD differs from origin/main, the branch under test is never entered, and the
// assertion would pass for the wrong reason.

const test = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')

const REPO = path.join(__dirname, '..')

const GIT_ENV = {
  GIT_AUTHOR_NAME: 't', GIT_AUTHOR_EMAIL: 't@t',
  GIT_COMMITTER_NAME: 't', GIT_COMMITTER_EMAIL: 't@t',
}

function git(args, cwd) {
  execFileSync('git', args, { cwd, stdio: 'ignore', env: { ...process.env, ...GIT_ENV } })
}

// A clone whose HEAD equals origin/main, carrying just enough of the repo for
// update.sh to run: itself, the adapters it sources, VERSION and plugins.json.
function makeCurrentClone() {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), '100x-clone-'))
  const origin = path.join(tmp, 'origin.git')
  const work = path.join(tmp, 'work')

  execFileSync('git', ['init', '--bare', '-b', 'main', origin], { stdio: 'ignore' })
  execFileSync('git', ['clone', origin, work], { stdio: 'ignore', env: { ...process.env, ...GIT_ENV } })

  fs.mkdirSync(path.join(work, 'adapters', 'lib'), { recursive: true })
  fs.mkdirSync(path.join(work, 'plugins'), { recursive: true })
  fs.copyFileSync(path.join(REPO, 'update.sh'), path.join(work, 'update.sh'))
  for (const f of ['deprecated.sh', 'shared.sh', 'modules.py', 'sync_plugins.py']) {
    fs.copyFileSync(path.join(REPO, 'adapters', 'lib', f), path.join(work, 'adapters', 'lib', f))
  }
  for (const f of ['cursor.sh', 'codex.sh']) {
    fs.copyFileSync(path.join(REPO, 'adapters', f), path.join(work, 'adapters', f))
  }
  fs.writeFileSync(path.join(work, 'VERSION'), '3.0.0\n')
  fs.writeFileSync(path.join(work, 'plugins', 'plugins.json'), JSON.stringify({ plugins: [] }))

  git(['add', '-A'], work)
  git(['commit', '-m', 'seed'], work)
  git(['push', 'origin', 'main'], work)
  git(['fetch', 'origin', 'main'], work)

  const head = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: work, encoding: 'utf8' }).trim()
  const remote = execFileSync('git', ['rev-parse', 'origin/main'], { cwd: work, encoding: 'utf8' }).trim()
  assert.equal(head, remote, 'precondition: clone must be on the already-current path')

  return work
}

function runUpdate(work, args, home) {
  try {
    return execFileSync('bash', [path.join(work, 'update.sh'), ...args], {
      encoding: 'utf8',
      env: { ...process.env, HOME: home, CLAUDE_BIN: '/usr/bin/false' },
      stdio: ['ignore', 'pipe', 'pipe'],
    })
  } catch (e) {
    return (e.stdout || '') + (e.stderr || '')
  }
}

function trackedProject(home) {
  const project = fs.mkdtempSync(path.join(os.tmpdir(), '100x-proj-'))
  fs.writeFileSync(path.join(project, 'GEMINI.md'), '# Generated by 100xprism\nbody\n')
  fs.mkdirSync(path.join(home, '.100xprism'), { recursive: true })
  fs.writeFileSync(path.join(home, '.100xprism', 'tracked-projects'), project + '\n')
  return project
}

test('--check-only does not delete deprecated artifacts when already up to date', () => {
  const work = makeCurrentClone()
  const home = fs.mkdtempSync(path.join(os.tmpdir(), '100x-home-'))
  const project = trackedProject(home)

  const out = runUpdate(work, ['--check-only'], home)

  assert.match(out, /already up to date/i, 'entered the already-current branch under test')
  assert.ok(
    fs.existsSync(path.join(project, 'GEMINI.md')),
    `--check-only must not delete project files. Output:\n${out}`,
  )
  assert.match(out, /skipping project reconciliation/, 'says why it skipped')
})

test('a normal update on the already-current path still performs the migration', () => {
  // Counterpart: skipping under --check-only must not disable the retry that
  // lets an interrupted migration finish on a later run.
  const work = makeCurrentClone()
  const home = fs.mkdtempSync(path.join(os.tmpdir(), '100x-home-'))
  const project = trackedProject(home)

  const out = runUpdate(work, [], home)

  assert.match(out, /already up to date/i, 'same branch, without --check-only')
  assert.ok(
    !fs.existsSync(path.join(project, 'GEMINI.md')),
    `migration must still run when not in check-only mode. Output:\n${out}`,
  )
})

test('update refuses to run without HOME instead of aborting on an unbound variable', () => {
  let out
  try {
    out = execFileSync('env', ['-u', 'HOME', 'bash', path.join(REPO, 'update.sh'), '--check-only'], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'],
    })
  } catch (e) {
    out = (e.stdout || '') + (e.stderr || '')
  }
  assert.match(out, /HOME is not set/, 'explains the problem rather than "unbound variable"')
  assert.ok(!/unbound variable/.test(out), 'does not surface a raw set -u abort')
})
