#!/usr/bin/env bash
# deprecated.sh — removal of artifacts from tools 100xprism no longer supports.
# Source this file; do not execute directly.
#
# Windsurf, Copilot, Gemini, and Antigravity were dropped in v3.0.0. Their
# generated instruction files are dead weight in a project once support ends, so
# both `100xprism update` (across every tracked project) and `100xprism init`
# (for the project being initialised) prune them.
#
# Only files carrying our generation marker are touched — a hand-written
# .windsurfrules or GEMINI.md is never removed.

DEPRECATED_ARTIFACTS=(
  ".windsurfrules"
  "GEMINI.md"
  "ANTIGRAVITY.md"
  ".github/copilot-instructions.md"
)

# prune_deprecated_artifacts <project_path>
# Echoes one line per removed file. Sets PRUNED_COUNT to the number removed.
prune_deprecated_artifacts() {
  local project_path="$1"
  local f
  PRUNED_COUNT=0

  for f in "${DEPRECATED_ARTIFACTS[@]}"; do
    [[ -f "$project_path/$f" ]] || continue
    # Only prune what we generated — our adapters stamped every file with this.
    grep -q "Generated by 100xprism" "$project_path/$f" 2>/dev/null || continue
    rm -f "$project_path/$f" && PRUNED_COUNT=$((PRUNED_COUNT + 1))
    echo "     removed $f"
  done

  return 0
}
