#!/usr/bin/env bash
# deprecated.sh — removal of artifacts from tools 100xprism no longer supports.
# Source this file; do not execute directly.
#
# Windsurf, Copilot, Gemini, and Antigravity were dropped in v3.0.0. Their
# generated instruction files are dead weight once support ends, so both
# `100xprism update` (across every tracked project) and `100xprism init` (for
# the project being initialised) prune them.
#
# This deletes files inside a user's repository, so it is deliberately paranoid:
#
#   1. Ownership — the file must carry our generation marker in its header
#      region. A hand-written .windsurfrules is never touched.
#   2. Containment — the resolved path must still live inside the resolved
#        project directory. A symlinked `.github` pointing at a shared config
#        directory must not let a delete escape into another repository.
#   3. Recoverability — every file is copied into
#      ~/.100xprism/removed-artifacts/<timestamp>/ before it is removed, and is
#      only removed if that copy succeeded. Nothing this function deletes is
#      unrecoverable, even for edits that were never committed.
#
# Failures are reported, never swallowed: PRUNE_FAILED counts files we wanted to
# remove but could not.

DEPRECATED_ARTIFACTS=(
  ".windsurfrules"
  "GEMINI.md"
  "ANTIGRAVITY.md"
  ".github/copilot-instructions.md"
)

# Our adapters stamped every generated file with this in the header block.
DEPRECATED_MARKER="Generated by 100xprism"
# Lines of header to search. Generated files carry the marker on line 2; a
# generous window tolerates format drift without matching prose deep in a body.
DEPRECATED_MARKER_LINES=10

# _resolve_dir <path> — absolute, symlink-resolved directory path ('' if absent).
_resolve_dir() {
  [[ -d "$1" ]] || return 1
  (cd "$1" 2>/dev/null && pwd -P) || return 1
}

# prune_backup_root — one backup directory per run, created on first use.
# Callers looping over many projects should set this once so every removal from a
# single run lands under the same root and can be reported as one location.
prune_backup_root() {
  local home="${HOME:-}"
  if [[ -z "$home" ]]; then
    # Without HOME there is nowhere to guarantee recoverability. Return empty and
    # let the caller treat it as a backup failure rather than aborting under `set -u`.
    echo ""
    return 0
  fi
  echo "$home/.100xprism/removed-artifacts/$(date +%Y%m%d-%H%M%S)"
}

# prune_deprecated_artifacts <project_path> [backup_root]
# Sets PRUNED_COUNT (removed), PRUNE_FAILED (wanted to remove, could not), and
# PRUNE_BACKUP_DIR (where copies went, '' if nothing was removed).
prune_deprecated_artifacts() {
  local project_path="$1"
  local backup_root="${2:-}"
  local f real_project real_parent target rel slot
  PRUNED_COUNT=0
  PRUNE_FAILED=0
  PRUNE_BACKUP_DIR=""

  real_project="$(_resolve_dir "$project_path")" || return 0
  [[ -n "$backup_root" ]] || backup_root="$(prune_backup_root)"

  # Key the backup slot by the project's FULL resolved path, not its basename:
  # /work/client/app and /work/internal/app share a basename, and keying by that
  # let the second backup overwrite the first while both originals were deleted —
  # silently destroying the recoverability this function exists to guarantee.
  slot="$(printf '%s' "${real_project#/}" | tr '/' '_')"

  for f in "${DEPRECATED_ARTIFACTS[@]}"; do
    target="$project_path/$f"
    [[ -f "$target" ]] || continue

    # Containment: resolve the file's *directory* and require it to sit inside
    # the resolved project. Catches a symlinked .github escaping the repo.
    real_parent="$(_resolve_dir "$(dirname "$target")")" || continue
    case "$real_parent" in
      "$real_project"|"$real_project"/*) ;;
      *) echo "     skipped $f (resolves outside the project)"; continue ;;
    esac

    # Ownership: marker must appear in the header region, not anywhere in the file.
    head -n "$DEPRECATED_MARKER_LINES" "$target" 2>/dev/null \
      | grep -q "$DEPRECATED_MARKER" || continue

    # Recoverability: copy first, and only delete if the copy landed. No backup
    # root (HOME unset) means no way to guarantee recovery, so refuse to delete.
    if [[ -z "$backup_root" ]]; then
      echo "     FAILED to back up $f (HOME unset) — leaving it in place"
      PRUNE_FAILED=$((PRUNE_FAILED + 1))
      continue
    fi
    rel="$backup_root/$slot/$f"
    if ! mkdir -p "$(dirname "$rel")" 2>/dev/null || ! cp -p "$target" "$rel" 2>/dev/null; then
      echo "     FAILED to back up $f — leaving it in place"
      PRUNE_FAILED=$((PRUNE_FAILED + 1))
      continue
    fi

    if rm -f "$target" 2>/dev/null; then
      PRUNED_COUNT=$((PRUNED_COUNT + 1))
      PRUNE_BACKUP_DIR="$backup_root"
      echo "     removed $f"
    else
      echo "     FAILED to remove $f"
      PRUNE_FAILED=$((PRUNE_FAILED + 1))
    fi
  done

  return 0
}
