#!/usr/bin/env python3
"""Single parser for modules/<slug>/SKILL.md.

Used by all adapters. Outputs JSON to stdout with one of these subcommands:

  list                       — full manifest (all modules, sorted by category/name)
  detect-profiles <dir>      — JSON: profiles a project looks like + resulting split
  emit-cursor <project_dir>  — write .cursor/rules/<slug>.mdc per module
  emit-codex <project_dir>   — write Codex-native AGENTS.md, repo skills, hooks
  emit-pi <project_dir>      — write retention-filtered .pi/skills (+ prompts, catalog)
  emit-pi-package            — write filtered pi/skills for `pi install` (repo root)
  emit-claude-code           — write ~/.claude/skills/<slug>/* + ~/.claude/commands/<slug>.md
  emit-hooks [--sync]        — idempotently merge first-party hooks into
                               ~/.claude/settings.json from hooks/hooks.manifest.json.
                               Each hook is enabled per its manifest `default`, overridable
                               by its `toggle_env` env var (1/true=on, 0/false=off).
                               --sync only refreshes hooks already present (used on update).
"""
from __future__ import annotations

import json
import os
import shlex
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MODULES_DIR = REPO / "modules"
CODEX_HOOK_TEMPLATE = REPO / "adapters" / "templates" / "codex-run-hook.py"

# Markers + manifest let `emit-claude-code` prune ONLY 100xprism's own artifacts
# (never the user's hand-authored skills/commands) when a module is removed or
# merged upstream. See cmd_emit_claude_code.
GENERATED_MARKER = ".100xprism-generated"
ALIAS_MARKER = "<!-- 100xprism generated alias — regenerate, do not edit -->"
MANIFEST_NAME = ".100xprism-manifest.json"

# Cursor .mdc rules carry their marker in an HTML comment on line 7, below the
# frontmatter block. Both this emitter and the JS port in lib/adapters/windows.js
# must scan at least that far or pruning silently matches nothing.
CURSOR_MARKER = "generated by 100xprism"
CURSOR_MARKER_LINES = 10

# Modules removed in past releases. Cleaned up on update even for installs whose
# skills predate the manifest/marker (so they carry neither). Safe to trim once
# installs have cycled through a manifest-aware update.
REMOVED_MODULES = {"systems-architect", "conversion-copy"}

# Central model-routing map. Modules declare a bare alias (`model: haiku`) in
# frontmatter. Claude Code reads that alias natively and auto-resolves it to the
# latest version — so the alias is emitted verbatim there (see cmd_emit_claude_code,
# which copies frontmatter as-is). Every other adapter picks its own (often
# non-Claude) model, so they receive a vendor-neutral reasoning-tier hint instead of
# a Claude model name. `id`/`label` are the single source of truth for the deferred
# slash-command / documentation work; the emitters in this pass use `tier_hint`.
MODEL_ALIASES = {
    "haiku":  {"id": "claude-haiku-4-5",  "label": "Claude Haiku 4.5",  "tier_hint": "fast / low-cost (mechanical task)"},
    "sonnet": {"id": "claude-sonnet-5",   "label": "Claude Sonnet 5",   "tier_hint": "balanced (moderate reasoning)"},
    "opus":   {"id": "claude-opus-5",     "label": "Claude Opus 5",     "tier_hint": "most capable (deep reasoning)"},
}


def tier_annotation(model: str) -> str:
    """Vendor-neutral routing hint for non-Claude adapters. '' for unknown/empty alias."""
    info = MODEL_ALIASES.get(model.strip())
    return f"_Suggested model tier: {info['tier_hint']}_" if info else ""


# ── Retention classes ────────────────────────────────────────────────────────
# Every module's description is re-sent on every turn once it is installed as a
# real skill, so *installing* a module has a standing token cost while its body
# is free until invoked. Retention decides which modules earn that standing cost.
#
#   must     — deterministic machinery or house policy a model will not
#              reproduce unprompted (what commands `gate` runs, the order
#              `release` runs them in, the handoff protocol `pair-loop` speaks).
#              Installed everywhere, always.
#   profile  — earns its place only in repos of a matching kind.
#   resolver — general expertise a capable model already has. Never installed as
#              a skill; appears as one row in the generated resolver catalog and
#              is loaded by path on demand.
#
# A module may override the derived class with `retention:` in its frontmatter.
RETENTION_CLASSES = ("must", "profile", "resolver")

MUST_HAVE = {
    "gate", "commit", "push", "branch", "pr", "release",
    "test", "lint", "security", "docs", "eval", "pair-loop",
}

# Categories whose modules are advice-shaped by default. Overridden per module by
# `retention:`, and never applied to a module that owns a slash command — the user
# can type that command, so the skill has to exist.
RESOLVER_CATEGORIES = {"marketing", "design"}

# Which repos a module earns its standing cost in. Derived from category unless a
# module declares `profiles:`. "core" is implicitly active in every project.
CATEGORY_PROFILES = {
    "lifecycle": ["core"],
    "quality": ["core"],
    "engineering": ["code"],
    "docs": ["code"],
    "data": ["data"],
    "design": ["design"],
    "marketing": ["growth"],
}
KNOWN_PROFILES = ("core", "code", "data", "design", "growth")


def retention_of(fm: dict, slug: str, category: str, slash_command: str) -> str:
    """Derived retention class, overridable by frontmatter `retention:`."""
    declared = fm.get("retention", "").strip()
    if declared in RETENTION_CLASSES:
        return declared
    if slug in MUST_HAVE:
        return "must"
    # An invocable command must resolve to a real skill, whatever its category.
    if slash_command:
        return "profile"
    if category in RESOLVER_CATEGORIES:
        return "resolver"
    return "profile"


def profiles_of(fm: dict, category: str) -> list[str]:
    """Derived profile list, overridable by frontmatter `profiles: a, b`."""
    declared = [p.strip() for p in fm.get("profiles", "").replace(",", " ").split() if p.strip()]
    if declared:
        return declared
    return list(CATEGORY_PROFILES.get(category, ["core"]))


def short_description(desc: str) -> str:
    """First sentence of a description, capped at 140 chars — for tight rule triggering."""
    d = desc.split(". ", 1)[0]
    if len(d) > 140:
        d = d[:137] + "..."
    return d


def render_command_alias(fm: dict, slug: str, body: str) -> str:
    """Slash-command alias that mirrors the skill's routing/guardrails in frontmatter.

    Commands and skills share a frontmatter schema, so the alias carries description,
    model routing, and allowed-tools instead of dropping them. argument-hint is emitted
    generically only when the body actually consumes positional input.
    """
    lines = ["---", f"description: {short_description(fm.get('description', ''))}"]
    model = fm.get("model", "").strip()
    if model:
        lines.append(f"model: {model}")
    allowed = fm.get("allowed-tools", "").strip()
    if allowed:
        lines.append(f"allowed-tools: {allowed}")
    if "$ARGUMENTS" in body or "$1" in body:
        lines.append("argument-hint: [arguments]")
    lines += ["---", "", ALIAS_MARKER, "", f"Use the `{fm.get('name', slug)}` skill.", "", "$ARGUMENTS", ""]
    return "\n".join(lines)


def split_frontmatter(text: str) -> tuple[dict, str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}, text
    fm_block = text[4:end]
    body = text[end + 5 :]
    fm: dict[str, str] = {}
    current_key: str | None = None
    for line in fm_block.splitlines():
        if not line.strip():
            continue
        if line.startswith(" ") and current_key:
            fm[current_key] = (fm[current_key] + " " + line.strip()).strip()
            continue
        if ":" in line:
            key, _, val = line.partition(":")
            current_key = key.strip()
            fm[current_key] = val.strip()
    return fm, body


def list_modules() -> list[dict]:
    out: list[dict] = []
    for skill_md in sorted(MODULES_DIR.glob("*/SKILL.md")):
        fm, body = split_frontmatter(skill_md.read_text())
        category = fm.get("category", "uncategorized")
        slash_command = fm.get("slash_command", "")
        slug = skill_md.parent.name
        out.append({
            "slug": slug,
            "name": fm.get("name", slug),
            "description": fm.get("description", ""),
            "category": category,
            "tier": fm.get("tier", "on-demand"),
            "retention": retention_of(fm, slug, category, slash_command),
            "profiles": profiles_of(fm, category),
            "slash_command": slash_command,
            "allowed_tools": fm.get("allowed-tools", ""),
            "model": fm.get("model", ""),
            "body": body,
            "dir": str(skill_md.parent),
        })
    out.sort(key=lambda m: (m["tier"] != "core", m["category"], m["slug"]))
    return out


# ── Per-project profile resolution ───────────────────────────────────────────
# Filtering is OFF unless a project opts in, so an emit into a bare directory
# behaves exactly as it did before profiles existed. `100xprism init` and
# `100xprism slim` write the config that turns it on; `profiles: ["all"]` in that
# config turns it back off again without deleting the file.
PROJECT_CONFIG = ".100xprism.json"

# Ordered so the first match wins for reporting purposes; a repo can match several.
PROFILE_MARKERS = {
    "code": [
        "package.json", "pyproject.toml", "setup.py", "requirements.txt", "go.mod",
        "Cargo.toml", "pom.xml", "build.gradle", "Gemfile", "composer.json",
        "tsconfig.json", "CMakeLists.txt",
    ],
    "data": [
        "terraform", "dbt_project.yml", "docker-compose.yml", "docker-compose.yaml",
        "migrations", "alembic.ini", "Dockerfile",
    ],
    "design": [
        "tailwind.config.js", "tailwind.config.ts", "tailwind.config.cjs",
        ".storybook", "components", "src/components",
    ],
    "growth": [
        "content", "posts", "_posts", "blog", "marketing", "landing",
        "next-sitemap.config.js", "public/robots.txt",
    ],
}


def detect_profiles(project_dir: str | Path) -> list[str]:
    """Best-effort repo classification. Always includes 'core'.

    A repo with no recognisable marker at all gets 'growth' as well as 'core' —
    a bare content/docs directory is the case that would otherwise silently lose
    every module it might actually want.
    """
    project = Path(project_dir)
    found = ["core"]
    for profile in ("code", "data", "design", "growth"):
        if any((project / marker).exists() for marker in PROFILE_MARKERS[profile]):
            found.append(profile)
    if found == ["core"]:
        found.append("growth")
    return found


def read_project_config(project_dir: str | Path) -> dict:
    try:
        return json.loads((Path(project_dir) / PROJECT_CONFIG).read_text())
    except (OSError, ValueError):
        return {}


def active_profiles(project_dir: str | Path) -> list[str] | None:
    """Profiles to filter by; [] means must-only and None explicitly means all.

    Precedence: PRISM_PROFILES env override → project config → lean default. Both
    the env var and the config accept "all" as an explicit opt-out of filtering.
    """
    env = os.environ.get("PRISM_PROFILES", "").strip()
    if env:
        vals = [p.strip() for p in env.replace(",", " ").split() if p.strip()]
        if "all" in vals:
            return None
        return sorted(set(vals) | {"core"})

    cfg = read_project_config(project_dir).get("profiles")
    if not cfg:
        return []
    if isinstance(cfg, str):
        cfg = [cfg]
    if "all" in cfg:
        return None
    return sorted({str(p).strip() for p in cfg if str(p).strip()} | {"core"})


def select_modules(modules: list[dict], profiles: list[str] | None) -> tuple[list[dict], list[dict]]:
    """Split into (installed as real artifacts, resolver-only).

    With no active profiles this keeps every non-resolver module, which is what
    every pre-profiles caller got. `must` modules ignore profiles by definition.
    """
    keep: list[dict] = []
    catalog: list[dict] = []
    for m in modules:
        if m["retention"] == "resolver":
            catalog.append(m)
        elif m["retention"] == "must" or profiles is None:
            keep.append(m)
        elif set(m["profiles"]) & set(profiles):
            keep.append(m)
        else:
            catalog.append(m)
    return keep, catalog


CATEGORY_ORDER = [
    "lifecycle", "quality", "engineering", "data", "design", "docs", "marketing", "uncategorized"
]


def category_sort_key(c: str) -> int:
    try:
        return CATEGORY_ORDER.index(c)
    except ValueError:
        return len(CATEGORY_ORDER)


def emit_index(modules: list[dict], indent: str = "") -> str:
    """One-line-per-module index, grouped by category. Used for on-demand listing."""
    lines: list[str] = []
    by_cat: dict[str, list[dict]] = {}
    for m in modules:
        by_cat.setdefault(m["category"], []).append(m)
    for cat in sorted(by_cat.keys(), key=category_sort_key):
        lines.append(f"{indent}**{cat.title()}** ({len(by_cat[cat])}):")
        for m in by_cat[cat]:
            slash = f" `{m['slash_command']}`" if m["slash_command"] else ""
            d = short_description(m["description"])
            tier = tier_annotation(m.get("model", ""))
            tier_suffix = f" {tier}" if tier else ""
            lines.append(f"{indent}- `{m['slug']}`{slash} — {d}{tier_suffix}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ── Resolver ─────────────────────────────────────────────────────────────────
# One always-on artifact replacing N always-on descriptions. Its own description
# is the only standing cost; the catalog table in its body is read on the turns
# that actually need to route, and the module body itself on the turn after that.
RESOLVER_SLUG = "100x-resolver"
CATALOG_DIRNAME = "100xprism-catalog"

RESOLVER_DESCRIPTION = (
    "Catalog of specialist 100xprism workflows kept out of the always-on index — "
    "marketing, SEO, CRO, copywriting, growth, pricing, sales, design, accessibility, "
    "motion, and data-visualization playbooks. Read this file's table to find the right "
    "one, then read that module's SKILL.md path before starting the work."
)


def user_skills_mode() -> str:
    """How much of the catalog gets installed as real user-scope skills.

    'must' is the lean default. Set by `100xprism optimize`/`slim`, or per-run via
    PRISM_SKILLS. Unknown values fail closed to 'must' instead of widening context.
    """
    env = os.environ.get("PRISM_SKILLS", "").strip().lower()
    if env in ("all", "profile", "must"):
        return env
    if env:
        return "must"
    try:
        cfg = json.loads((Path.home() / ".100xprism" / "config.json").read_text())
    except (OSError, ValueError):
        return "must"
    mode = str(cfg.get("skills", "must")).strip().lower()
    return mode if mode in ("all", "profile", "must") else "must"


def split_by_mode(modules: list[dict], mode: str) -> tuple[list[dict], list[dict]]:
    """(installed, catalog) for a user-scope skills mode."""
    if mode == "all":
        return list(modules), []
    if mode == "must":
        keep = [m for m in modules if m["retention"] == "must"]
    else:  # profile
        keep = [m for m in modules if m["retention"] in ("must", "profile")]
    kept = {m["slug"] for m in keep}
    return keep, [m for m in modules if m["slug"] not in kept]


def render_catalog_table(catalog: list[dict], path_template: str) -> str:
    """Markdown table: one row per catalog module, grouped by category.

    `path_template` is formatted with `slug` and tells the agent exactly what to
    read — a row is only useful if it resolves to a file without further search.
    """
    if not catalog:
        return "_No catalog modules — every module is installed as a skill._\n"
    by_cat: dict[str, list[dict]] = {}
    for m in catalog:
        by_cat.setdefault(m["category"], []).append(m)
    lines: list[str] = []
    for cat in sorted(by_cat.keys(), key=category_sort_key):
        lines.append(f"\n### {cat.title()}\n")
        lines.append("| Module | Use it when | Read |")
        lines.append("|---|---|---|")
        for m in sorted(by_cat[cat], key=lambda x: x["slug"]):
            trigger = short_description(m["description"]).replace("|", "\\|")
            lines.append(f"| `{m['slug']}` | {trigger} | `{path_template.format(slug=m['slug'])}` |")
    return "\n".join(lines) + "\n"


def render_resolver(catalog: list[dict], path_template: str) -> str:
    """The resolver artifact's SKILL.md."""
    return (
        "---\n"
        f"name: {RESOLVER_SLUG}\n"
        f"description: {RESOLVER_DESCRIPTION}\n"
        "category: docs\n"
        "tier: on-demand\n"
        "---\n\n"
        f"# 100xprism catalog ({len(catalog)} modules)\n\n"
        "These modules are deliberately not in the always-on skill index. Find the row "
        "that matches the task, **read the file in its `Read` column**, then follow it as "
        "you would any skill. If nothing matches, proceed without one.\n"
        + render_catalog_table(catalog, path_template)
    )


def render_generic_route(argument_expr: str = "$ARGUMENTS") -> str:
    """One compact command/prompt replacing resident aliases for routed modules."""
    return (
        "---\n"
        "description: Load any routed 100xprism workflow by slug without indexing every workflow.\n"
        "argument-hint: <workflow> [arguments]\n"
        "---\n\n"
        f"{ALIAS_MARKER}\n\n"
        "Use the `100x-resolver` skill. Find the workflow named by the first argument, "
        "read its catalog SKILL.md path, and follow it with the remaining arguments.\n\n"
        f"{argument_expr}\n"
    )


def render_codex_agents(modules: list[dict]) -> str:
    """Compact Codex project guidance.

    Codex has a default AGENTS.md byte budget, while repo skills load through
    progressive disclosure. Keep AGENTS.md as routing/orientation text and emit
    full module bodies into .agents/skills instead.
    """
    out = [
        "# 100x Dev for Codex\n",
        "# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n",
        "# Source of truth: modules/<slug>/SKILL.md. Regenerate instead of hand-editing.\n\n",
        "## How Codex Should Use 100x Dev\n\n",
        "- Full reusable workflows live in `.agents/skills/<slug>/SKILL.md` so Codex can load them on demand.\n",
        "- When the user names a 100xprism slash workflow like `/gate`, treat it as a request to use the matching skill in `.agents/skills/`.\n",
        "- Prefer explicit skill invocation (`$gate`, `$commit`, `$test`, etc.) or `/skills` when available; custom prompt slash commands are intentionally not generated.\n",
        "- The generated `.agents/100x-index.md` contains the full module catalog when you need to browse available skills.\n",
        "- Codex hooks, when generated, live in `.codex/hooks.json`. Review and trust them with `/hooks` before expecting enforcement.\n",
        "- Claude Code plugins in `plugins/plugins.json` are not Codex plugins. Use Codex `/plugins` for Codex-native plugins and app/MCP integrations.\n\n",
        "## 100xprism Command Map\n\n",
    ]

    commands = [m for m in modules if m["slash_command"]]
    for m in sorted(commands, key=lambda x: x["slash_command"]):
        out.append(f"- `{m['slash_command']}` → `${m['slug']}` — {short_description(m['description'])}\n")

    return "".join(out)


def render_codex_index(modules: list[dict]) -> str:
    """Render the browseable module catalog outside Codex's always-loaded router."""
    return (
        "# 100xprism Skill Index\n\n"
        "Generated by 100xprism from `modules/<slug>/SKILL.md`. Full bodies are in "
        "`.agents/skills/<slug>/SKILL.md`; regenerate instead of hand-editing.\n\n"
        + emit_index(modules)
    )


def cmd_list():
    mods = list_modules()
    print(json.dumps(mods, indent=2))


def cmd_detect_profiles(project_dir: str):
    """Report the profiles a project looks like, for `100xprism slim`."""
    profiles = detect_profiles(project_dir)
    mods = list_modules()
    keep, catalog = select_modules(mods, profiles)
    print(json.dumps({
        "profiles": profiles,
        "installed": len(keep),
        "catalog": len(catalog),
    }, indent=2))


def _write_catalog_bodies(catalog: list[dict], catalog_dir: Path) -> None:
    """Park catalog module bodies on disk, outside anything the tool indexes.

    Cleared and rewritten wholesale: everything under this directory is ours, so
    a module that graduates back into the skill index leaves no stale copy behind.
    """
    if catalog_dir.exists():
        shutil.rmtree(catalog_dir)
    if not catalog:
        return
    catalog_dir.mkdir(parents=True, exist_ok=True)
    for m in catalog:
        target = catalog_dir / m["slug"]
        shutil.copytree(m["dir"], target)
        (target / GENERATED_MARKER).write_text(
            "Generated by 100xprism from modules/<slug>/SKILL.md. Regenerate instead of editing here.\n"
        )


def cmd_emit_cursor(project_dir: str):
    rules_dir = Path(project_dir) / ".cursor" / "rules"
    if rules_dir.exists():
        # Remove only files we previously wrote (those with our generation marker).
        # The marker sits on line 7 — after the 5-line frontmatter block and its
        # trailing blank — so the window must reach past it. It was 6 for a long
        # time, which silently matched nothing and orphaned every removed module's
        # rule. See test_cursor_prune_removes_real_generated_rule.
        for f in rules_dir.glob("*.mdc"):
            try:
                head = f.read_text().splitlines()[:CURSOR_MARKER_LINES]
                if any(CURSOR_MARKER in line for line in head):
                    f.unlink()
            except OSError:
                pass
    rules_dir.mkdir(parents=True, exist_ok=True)
    mods = list_modules()

    # Fresh emits are must-only. Explicit project profiles widen the index and
    # `profiles: ["all"]` restores the legacy unfiltered output.
    profiles = active_profiles(project_dir)
    keep, catalog = (mods, []) if profiles is None else select_modules(mods, profiles)

    def write_rule(slug: str, description: str, always_apply: str, model: str, body: str) -> None:
        cursor_fm = [
            "---",
            f"description: {description}",
            "globs:",
            f"alwaysApply: {always_apply}",
            "---",
            "",
            f"<!-- generated by 100xprism from modules/{slug}/SKILL.md -->",
            "",
        ]
        tier = tier_annotation(model)
        if tier:
            cursor_fm += [tier, ""]
        (rules_dir / f"{slug}.mdc").write_text("\n".join(cursor_fm) + body.lstrip("\n"))

    for m in keep:
        # Map tier to Cursor rule type: core modules are always in context;
        # on-demand modules are agent-requested via a tight first-sentence description.
        write_rule(
            m["slug"], short_description(m["description"]),
            "true" if m["tier"] == "core" else "false", m.get("model", ""), m["body"],
        )

    catalog_dir = Path(project_dir) / ".cursor" / CATALOG_DIRNAME
    _write_catalog_bodies(catalog, catalog_dir)
    if catalog:
        # The resolver is itself a rule, so Cursor can request it by description —
        # one description standing in for the descriptions of everything it lists.
        resolver_fm, resolver_body = split_frontmatter(
            render_resolver(catalog, f".cursor/{CATALOG_DIRNAME}/{{slug}}/SKILL.md")
        )
        write_rule(RESOLVER_SLUG, RESOLVER_DESCRIPTION, "false", "", resolver_body)

    suffix = f" (+{len(catalog)} in {CATALOG_DIRNAME}/)" if catalog else ""
    print(f"wrote {len(keep) + (1 if catalog else 0)} files to {rules_dir}{suffix}")


def cmd_emit_codex(project_dir: str):
    """Write Codex-native project artifacts.

    - AGENTS.md stays compact and under Codex's default project-doc budget.
    - .agents/skills contains the full module directories for progressive loading.
    - .codex/hooks.json wires first-party hooks for Codex's hook browser/trust flow.
    """
    project = Path(project_dir)
    mods = list_modules()

    profiles = active_profiles(project_dir)
    keep, catalog = (mods, []) if profiles is None else select_modules(mods, profiles)

    agents_file = project / "AGENTS.md"
    agents_file.parent.mkdir(parents=True, exist_ok=True)
    agents_file.write_text(render_codex_agents(keep))

    skills_dir = project / ".agents" / "skills"
    index_file = project / ".agents" / "100x-index.md"
    index_file.parent.mkdir(parents=True, exist_ok=True)
    index_file.write_text(render_codex_index(mods))
    catalog_dir = project / ".agents" / CATALOG_DIRNAME
    skill_count, _ = _write_pi_skill_tree(
        skills_dir, keep, catalog, catalog_dir,
        f".agents/{CATALOG_DIRNAME}/{{slug}}/SKILL.md",
    )

    hooks_dir = project / ".codex"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((HOOKS_DIR / "hooks.manifest.json").read_text())
    wrapper_dir = hooks_dir / "100xprism-hooks"
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    wrapper = wrapper_dir / "run-hook.py"
    wrapper.write_text(_codex_hook_wrapper(manifest))
    wrapper.chmod(0o755)

    hooks: dict[str, list[dict]] = {}
    hooks_opted_in = os.environ.get("PRISM_HOOKS", "").strip().lower() in (
        "1", "true", "yes", "on"
    )
    for hook in manifest.get("hooks", []):
        if not hooks_opted_in or not _hook_enabled(hook):
            continue
        command = _codex_hook_command(hook["script"])
        hooks.setdefault(hook["event"], []).append({
            "matcher": hook["matcher"],
            "hooks": [{
                "type": "command",
                "command": command,
                "statusMessage": f"100xprism: {hook['description']}",
            }],
        })
    (hooks_dir / "hooks.json").write_text(json.dumps({"hooks": hooks}, indent=2) + "\n")

    print(
        f"wrote Codex AGENTS.md + {skill_count} repo skills + "
        f"{sum(len(v) for v in hooks.values())} hook group(s) to {project}"
    )


def pi_active_profiles(project_dir: str | Path) -> list[str] | None:
    """Profiles for Pi emits. Fresh installs are must-only.

    - Explicit `profiles: ["all"]` / PRISM_PROFILES=all → no profile filter
      (still parks resolver-class modules in the catalog).
    - Explicit profile list → that list (+ core).
    - Unset or empty → [] (must-only).
    """
    env = os.environ.get("PRISM_PROFILES", "").strip()
    if env:
        vals = [p.strip() for p in env.replace(",", " ").split() if p.strip()]
        if "all" in vals:
            return None
        return sorted(set(vals) | {"core"})

    cfg = read_project_config(project_dir).get("profiles")
    if cfg is not None:
        if isinstance(cfg, str):
            cfg = [cfg]
        if not isinstance(cfg, list):
            return []
        if "all" in cfg:
            return None
        cleaned = [str(p).strip() for p in cfg if str(p).strip()]
        if not cleaned:
            return []
        return sorted(set(cleaned) | {"core"})

    return []


def render_pi_prompt_alias(slug: str, description: str) -> str:
    """One-liner prompt template that routes a slash alias to /skill:<slug>."""
    desc = short_description(description) or slug
    return (
        "---\n"
        f"description: {desc}\n"
        "---\n"
        f"Load and follow the 100xprism skill `/skill:{slug}` "
        f"(read its SKILL.md if needed). Arguments: ${{@ARGUMENTS:-}}\n"
    )


def render_pi_agents(modules: list[dict]) -> str:
    """Compact project AGENTS.md for Pi (same router budget idea as Codex)."""
    out = [
        "# 100x Dev for Pi\n",
        "# Generated by 100xprism (https://github.com/rajitsaha/100xprism)\n",
        "# Source of truth: modules/<slug>/SKILL.md. Regenerate instead of hand-editing.\n\n",
        "## How Pi Should Use 100x Dev\n\n",
        "- Retention-filtered skills live in `.pi/skills/<slug>/SKILL.md` "
        "(descriptions only until loaded).\n",
        "- Prefer `/skill:<slug>` (or a thin prompt alias when the slash name differs).\n",
        "- Resolver-class modules are listed by `100x-resolver` — read the catalog "
        "path, then the module body.\n",
        "- Gate/secret enforcement is a Pi extension, not resident markdown.\n",
        "- Claude Code plugins in `plugins/plugins.json` are not installed into Pi.\n\n",
        "## 100xprism Command Map\n\n",
    ]
    commands = [m for m in modules if m["slash_command"]]
    for m in sorted(commands, key=lambda x: x["slash_command"]):
        out.append(
            f"- `{m['slash_command']}` → `/skill:{m['slug']}` — "
            f"{short_description(m['description'])}\n"
        )
    return "".join(out)


def _prune_generated_skill_dirs(skills_dir: Path) -> None:
    if not skills_dir.exists():
        return
    for child in skills_dir.iterdir():
        if child.is_dir() and (child / GENERATED_MARKER).exists():
            shutil.rmtree(child)


def _write_pi_skill_tree(
    skills_dir: Path,
    keep: list[dict],
    catalog: list[dict],
    catalog_dir: Path,
    catalog_path_template: str,
) -> tuple[int, int]:
    """Write filtered skills + optional resolver. Returns (skill_count, prompt-ready alias count)."""
    skills_dir.mkdir(parents=True, exist_ok=True)
    _prune_generated_skill_dirs(skills_dir)
    skill_count = 0
    for m in keep:
        target = skills_dir / m["slug"]
        if target.exists():
            if (target / GENERATED_MARKER).exists():
                shutil.rmtree(target)
            else:
                print(f"skipped existing non-100xprism skill: {target}", file=sys.stderr)
                continue
        shutil.copytree(m["dir"], target)
        (target / GENERATED_MARKER).write_text(
            "Generated by 100xprism from modules/<slug>/SKILL.md. Regenerate instead of editing here.\n"
        )
        skill_count += 1

    _write_catalog_bodies(catalog, catalog_dir)
    if catalog:
        resolver_target = skills_dir / RESOLVER_SLUG
        if resolver_target.exists():
            shutil.rmtree(resolver_target)
        resolver_target.mkdir(parents=True)
        (resolver_target / "SKILL.md").write_text(
            render_resolver(catalog, catalog_path_template)
        )
        (resolver_target / GENERATED_MARKER).write_text(
            "Generated by 100xprism. Regenerate instead of editing here.\n"
        )
        skill_count += 1

    alias_n = sum(
        1 for m in keep
        if m["slash_command"] and m["slash_command"].lstrip("/") != m["slug"]
    )
    return skill_count, alias_n


def _write_pi_prompts(prompts_dir: Path, keep: list[dict]) -> int:
    prompts_dir.mkdir(parents=True, exist_ok=True)
    for f in list(prompts_dir.glob("*.md")):
        try:
            if "Generated by 100xprism" in f.read_text():
                f.unlink()
        except OSError:
            pass
    n = 0
    for m in keep:
        slash = m["slash_command"].lstrip("/")
        if not slash or slash == m["slug"]:
            continue
        (prompts_dir / f"{slash}.md").write_text(
            "---\n"
            f"description: {short_description(m['description']) or m['slug']}\n"
            "---\n"
            "<!-- Generated by 100xprism -->\n"
            f"Load and follow the 100xprism skill `/skill:{m['slug']}` "
            f"(read its SKILL.md if needed). Arguments: ${{@ARGUMENTS:-}}\n"
        )
        n += 1
    return n


def _write_pi_generic_prompt(prompts_dir: Path, catalog: list[dict]) -> int:
    if not catalog:
        return 0
    prompts_dir.mkdir(parents=True, exist_ok=True)
    (prompts_dir / "100x.md").write_text(render_generic_route("${@ARGUMENTS:-}"))
    return 1


def cmd_emit_pi(project_dir: str):
    """Write Pi project artifacts under .pi/ (retention ON by default)."""
    project = Path(project_dir)
    mods = list_modules()
    profiles = pi_active_profiles(project_dir)
    keep, catalog = select_modules(mods, profiles)

    pi_dir = project / ".pi"
    skills_dir = pi_dir / "skills"
    prompts_dir = pi_dir / "prompts"
    catalog_dir = pi_dir / CATALOG_DIRNAME

    skill_count, _ = _write_pi_skill_tree(
        skills_dir, keep, catalog, catalog_dir,
        f".pi/{CATALOG_DIRNAME}/{{slug}}/SKILL.md",
    )
    prompt_count = _write_pi_prompts(prompts_dir, keep)
    prompt_count += _write_pi_generic_prompt(prompts_dir, catalog)

    agents_file = project / "AGENTS.md"
    if not agents_file.exists():
        agents_file.write_text(render_pi_agents(keep))
        agents_note = " + AGENTS.md"
    else:
        agents_note = " (AGENTS.md left in place)"

    # Manifest for extensions / tests
    (pi_dir / ".100xprism-pi-manifest.json").write_text(json.dumps({
        "profiles": profiles,
        "skills": [m["slug"] for m in keep] + ([RESOLVER_SLUG] if catalog else []),
        "catalog": [m["slug"] for m in catalog],
    }, indent=2) + "\n")

    print(
        f"wrote {skill_count} Pi skills + {prompt_count} prompt alias(es) to {pi_dir}"
        f"{agents_note} (profiles={profiles})"
    )


def cmd_emit_pi_package():
    """Write package-local pi/skills for `pi install` (must-only default)."""
    mods = list_modules()
    keep, catalog = select_modules(mods, [])
    pi_dir = REPO / "pi"
    skills_dir = pi_dir / "skills"
    prompts_dir = pi_dir / "prompts"
    catalog_dir = pi_dir / CATALOG_DIRNAME

    skill_count, _ = _write_pi_skill_tree(
        skills_dir, keep, catalog, catalog_dir,
        f"pi/{CATALOG_DIRNAME}/{{slug}}/SKILL.md",
    )
    prompt_count = _write_pi_prompts(prompts_dir, keep)
    prompt_count += _write_pi_generic_prompt(prompts_dir, catalog)
    (pi_dir / ".100xprism-pi-manifest.json").write_text(json.dumps({
        "profiles": [],
        "skills": [m["slug"] for m in keep] + ([RESOLVER_SLUG] if catalog else []),
        "catalog": [m["slug"] for m in catalog],
    }, indent=2) + "\n")
    print(
        f"wrote package Pi tree: {skill_count} skills + {prompt_count} prompts → {pi_dir}"
    )


def _read_manifest(skills_dir: Path) -> dict:
    try:
        return json.loads((skills_dir / MANIFEST_NAME).read_text())
    except (OSError, ValueError):
        return {}


# Pre-rebrand marker names. Renamed in place so manifest/prune logic recognizes
# installs that were last emitted under the old `100x-dev` name.
_LEGACY_GENERATED_MARKER = ".100x-dev-generated"
_LEGACY_MANIFEST_NAME = ".100x-dev-manifest.json"
_LEGACY_ALIAS_MARKER = "<!-- 100x-dev generated alias — regenerate, do not edit -->"


def _migrate_legacy_markers(skills_dir: Path, commands_dir: Path) -> None:
    legacy_manifest = skills_dir / _LEGACY_MANIFEST_NAME
    if legacy_manifest.exists() and not (skills_dir / MANIFEST_NAME).exists():
        legacy_manifest.rename(skills_dir / MANIFEST_NAME)
    for child in skills_dir.iterdir():
        if not child.is_dir():
            continue
        legacy = child / _LEGACY_GENERATED_MARKER
        if legacy.exists() and not (child / GENERATED_MARKER).exists():
            legacy.rename(child / GENERATED_MARKER)
    for f in commands_dir.iterdir():
        if not f.is_file() or f.suffix != ".md":
            continue
        try:
            text = f.read_text()
        except OSError:
            continue
        if _LEGACY_ALIAS_MARKER in text:
            f.write_text(text.replace(_LEGACY_ALIAS_MARKER, ALIAS_MARKER))


def cmd_emit_claude_code():
    home = Path(os.environ.get("HOME", str(Path.home())))
    skills_dir = home / ".claude" / "skills"
    commands_dir = home / ".claude" / "commands"
    skills_dir.mkdir(parents=True, exist_ok=True)
    commands_dir.mkdir(parents=True, exist_ok=True)

    _migrate_legacy_markers(skills_dir, commands_dir)
    prev = _read_manifest(skills_dir)
    prev_skills = set(prev.get("skills", []))
    prev_cmds = set(prev.get("commands", []))

    current_slugs: list[str] = []
    current_cmds: list[str] = []
    skill_count = 0
    cmd_count = 0

    # `list_modules` already skips shared-reference dirs (e.g. `_lib/`, which holds
    # maintainer conventions in reference.md and has no SKILL.md).
    mode = user_skills_mode()
    installed, catalog = split_by_mode(list_modules(), mode)

    for m in installed:
        slug = m["slug"]
        target = skills_dir / slug
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(m["dir"], target)
        (target / GENERATED_MARKER).write_text(
            "Generated by 100xprism from modules/<slug>/SKILL.md. Regenerate instead of editing here.\n"
        )
        current_slugs.append(slug)
        skill_count += 1

        # Slash command alias ONLY when the command name differs from the slug
        # (e.g. fix-bugs → /fix). Claude Code already exposes every skill in
        # ~/.claude/skills as /<slug>, so a same-name alias would double-list the
        # module in the session's skill index and pay its description twice.
        fm, body = split_frontmatter((target / "SKILL.md").read_text())
        slash = fm.get("slash_command", "").lstrip("/")
        if slash and slash != slug:
            (commands_dir / f"{slash}.md").write_text(render_command_alias(fm, slug, body))
            current_cmds.append(slash)
            cmd_count += 1

    # Catalog bodies live beside ~/.claude, not inside skills/ — Claude Code indexes
    # every SKILL.md under skills/, so parking them there would keep charging the
    # description rent this split exists to remove.
    catalog_dir = home / ".100xprism" / CATALOG_DIRNAME
    _write_catalog_bodies(catalog, catalog_dir)
    if catalog:
        resolver_target = skills_dir / RESOLVER_SLUG
        if resolver_target.exists():
            shutil.rmtree(resolver_target)
        resolver_target.mkdir(parents=True)
        (resolver_target / "SKILL.md").write_text(
            render_resolver(catalog, str(catalog_dir / "{slug}" / "SKILL.md"))
        )
        (resolver_target / GENERATED_MARKER).write_text(
            "Generated by 100xprism. Regenerate instead of editing here.\n"
        )
        current_slugs.append(RESOLVER_SLUG)
        skill_count += 1
        (commands_dir / "100x.md").write_text(render_generic_route())
        current_cmds.append("100x")
        cmd_count += 1

    cur_skill_set = set(current_slugs)
    cur_cmd_set = set(current_cmds)

    # Prune orphaned skills: anything we previously emitted (manifest), carrying
    # our marker, or a known-removed module — that is no longer current. We only
    # ever rmtree dirs that are unambiguously ours.
    orphan_skills = (prev_skills | REMOVED_MODULES) - cur_skill_set
    for child in skills_dir.iterdir():
        if child.is_dir() and child.name not in cur_skill_set and (child / GENERATED_MARKER).exists():
            orphan_skills.add(child.name)
    pruned_skills = 0
    for slug in sorted(orphan_skills):
        p = skills_dir / slug
        if p.is_dir() and ((p / GENERATED_MARKER).exists() or slug in prev_skills or slug in REMOVED_MODULES):
            shutil.rmtree(p)
            pruned_skills += 1

    # Prune orphaned slash-command aliases we previously wrote (marker-guarded so
    # a user's own command of the same name is never deleted).
    pruned_cmds = 0
    for name in sorted(prev_cmds - cur_cmd_set):
        f = commands_dir / f"{name}.md"
        try:
            if f.is_file() and ALIAS_MARKER in f.read_text():
                f.unlink()
                pruned_cmds += 1
        except OSError:
            pass

    (skills_dir / MANIFEST_NAME).write_text(
        json.dumps({"skills": sorted(current_slugs), "commands": sorted(current_cmds)}, indent=2) + "\n"
    )

    suffix = ""
    if pruned_skills or pruned_cmds:
        suffix = f" (pruned {pruned_skills} stale skill(s), {pruned_cmds} stale alias(es))"
    catalog_note = f" + {len(catalog)} catalog module(s) behind {RESOLVER_SLUG}" if catalog else ""
    print(f"wrote {skill_count} skills + {cmd_count} slash command aliases{catalog_note}{suffix}")


HOOKS_DIR = REPO / "hooks"


def _hook_command(script: str) -> str:
    return f'python3 "{HOOKS_DIR / script}"'


def _codex_hook_command(script: str) -> str:
    return f"python3 .codex/100xprism-hooks/run-hook.py {shlex.quote(script)}"


def _codex_hook_wrapper(manifest: dict) -> str:
    allowed = sorted(
        hook["script"]
        for hook in manifest.get("hooks", [])
        if isinstance(hook, dict) and hook.get("script")
    )
    return CODEX_HOOK_TEMPLATE.read_text().replace(
        "__ALLOWED_HOOKS_JSON__",
        json.dumps(allowed, separators=(",", ":")),
    )


def _hook_enabled(hook: dict) -> bool:
    """manifest `default`, overridden by the hook's `toggle_env` env var if set."""
    env = hook.get("toggle_env")
    if env and env in os.environ:
        val = os.environ[env].strip().lower()
        if val in ("1", "true", "yes", "on"):
            return True
        if val in ("0", "false", "no", "off", ""):
            return False
    return bool(hook.get("default"))


def _command_present(entries: list, command: str) -> bool:
    return any(
        h.get("command") == command
        for e in entries
        for h in e.get("hooks", [])
    )


def _strip_command(entries: list, command: str) -> list:
    """Remove our command from every entry; drop entries left with no hooks."""
    out = []
    for e in entries:
        kept = [h for h in e.get("hooks", []) if h.get("command") != command]
        if kept:
            out.append({**e, "hooks": kept})
    return out


def _strip_stale_managed_commands(entries: list, valid_commands: set[str]) -> tuple[list, int]:
    """Remove only obsolete hook commands whose path proves 100xprism ownership."""
    out, removed = [], 0
    for entry in entries:
        kept_hooks = []
        for hook in entry.get("hooks", []):
            command = str(hook.get("command", ""))
            normalized = command.replace("\\\\", "/")
            managed = "/100xprism/hooks/" in normalized
            if managed and command not in valid_commands:
                removed += 1
            else:
                kept_hooks.append(hook)
        if kept_hooks:
            out.append({**entry, "hooks": kept_hooks})
    return out, removed


def cmd_emit_hooks(sync: bool = False):
    """Idempotently merge first-party hooks into settings.json (declarative).

    For each manifest hook we strip any existing copy of its command, then re-add a
    single entry when it should be enabled — so re-running never duplicates entries and
    flipping a toggle off removes the hook. `sync` keeps only hooks already present
    (used on update, so we never silently enable a hook the user opted out of).
    """
    manifest = json.loads((HOOKS_DIR / "hooks.manifest.json").read_text())
    hooks_spec = manifest.get("hooks", [])

    settings_file = Path(
        os.environ.get("SETTINGS_FILE")
        or os.path.expanduser("~/.claude/settings.json")
    )
    settings_file.parent.mkdir(parents=True, exist_ok=True)
    try:
        settings = json.loads(settings_file.read_text())
    except (OSError, json.JSONDecodeError):
        settings = {}

    settings_hooks = settings.setdefault("hooks", {})
    valid_commands = {_hook_command(hook["script"]) for hook in hooks_spec}
    stale_removed = 0
    for event, entries in list(settings_hooks.items()):
        cleaned, count = _strip_stale_managed_commands(entries, valid_commands)
        stale_removed += count
        if cleaned:
            settings_hooks[event] = cleaned
        else:
            del settings_hooks[event]
    added, kept, removed = [], [], []

    for hook in hooks_spec:
        command = _hook_command(hook["script"])
        event = hook["event"]
        entries = settings_hooks.get(event, [])
        was_present = _command_present(entries, command)
        entries = _strip_command(entries, command)  # dedupe / declarative reset

        keep = was_present if sync else _hook_enabled(hook)
        if keep:
            entries.append({
                "matcher": hook["matcher"],
                "hooks": [{"type": "command", "command": command}],
            })
            (kept if was_present else added).append(hook["id"])
        elif was_present:
            removed.append(hook["id"])

        if entries:
            settings_hooks[event] = entries
        elif event in settings_hooks:
            del settings_hooks[event]

    settings_file.write_text(json.dumps(settings, indent=2))

    parts = []
    if added:
        parts.append(f"added {len(added)} ({', '.join(added)})")
    if kept:
        parts.append(f"refreshed {len(kept)}")
    if removed:
        parts.append(f"removed {len(removed)} ({', '.join(removed)})")
    if stale_removed:
        parts.append(f"removed {stale_removed} stale managed command(s)")
    print(f"hooks: {'; '.join(parts) if parts else 'no changes'} → {settings_file}")


def main(argv: list[str]):
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    cmd = argv[1]
    if cmd == "list":
        cmd_list()
    elif cmd == "detect-profiles":
        cmd_detect_profiles(argv[2] if len(argv) > 2 else ".")
    elif cmd == "emit-cursor":
        cmd_emit_cursor(argv[2])
    elif cmd == "emit-codex":
        cmd_emit_codex(argv[2])
    elif cmd == "emit-pi":
        cmd_emit_pi(argv[2] if len(argv) > 2 else ".")
    elif cmd == "emit-pi-package":
        cmd_emit_pi_package()
    elif cmd == "emit-claude-code":
        cmd_emit_claude_code()
    elif cmd == "emit-hooks":
        cmd_emit_hooks(sync="--sync" in argv[2:])
    else:
        print(f"unknown command: {cmd}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
