#!/usr/bin/env bash
# shared.sh — common logic for all 100x-dev adapter scripts
# Source this file; do not execute directly.

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$_LIB_DIR/../.." && pwd)"
WORKFLOWS_DIR="$REPO_DIR/workflows"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# generate_adapter <output_file_relative> <display_name> [warning_message]
#
#   output_file_relative  — path relative to project_path (e.g. ".cursorrules"
#                           or ".github/copilot-instructions.md")
#   display_name          — label used in echo output (e.g. "Cursor")
#   warning_message       — optional; when set, printed in yellow before generation
#
# The function is wrapped by each adapter's install_project(), which receives
# the project path as $1.
generate_adapter() {
  local output_rel="$1"
  local display_name="$2"
  local warning_message="${3:-}"

  # install_project is defined in the sourcing script and passes project_path here
  # We use a second-level wrapper so callers just define install_project().
  # This helper is invoked from within install_project, so project_path is local
  # to the caller — we accept it as an implicit fourth arg for flexibility, but
  # the common pattern is: callers call _run_generate directly.
  :  # no-op; real work is in _run_generate below
}

# _run_generate <project_path> <output_file_relative> <display_name> [warning_message]
#
# Called by each adapter's install_project().
_run_generate() {
  local project_path="$1"
  local output_rel="$2"
  local display_name="$3"
  local warning_message="${4:-}"

  local output_file="$project_path/$output_rel"

  # Create parent directory if the output path contains a subdirectory
  local parent_dir
  parent_dir="$(dirname "$output_file")"
  mkdir -p "$parent_dir"

  echo ""
  echo "Generating $output_rel for $display_name..."

  if [[ -n "$warning_message" ]]; then
    echo -e "${YELLOW}${warning_message}${NC}"
  fi

  {
    echo "# 100x Dev Workflows"
    echo "# Generated by 100x-dev (https://github.com/rajitsaha/100x-dev)"
    echo "# Regenerate: run install.sh or adapters/$(basename "${BASH_SOURCE[1]}") <project-path>"
    echo ""

    for f in gate test commit push pr branch launch lint security docs issue architect cloud-security enterprise-design db; do
      if [ -f "$WORKFLOWS_DIR/$f.md" ]; then
        echo "---"
        echo ""
        cat "$WORKFLOWS_DIR/$f.md"
        echo ""
      fi
    done
  } > "$output_file"

  # Record project path for auto-regeneration on update
  local _tracked_file="$HOME/.100x-dev/tracked-projects"
  mkdir -p "$(dirname "$_tracked_file")"
  local _abs_path
  _abs_path="$(cd "$project_path" && pwd)"
  if ! grep -qxF "$_abs_path" "$_tracked_file" 2>/dev/null; then
    echo "$_abs_path" >> "$_tracked_file"
  fi

  echo -e "  ${GREEN}→ Generated $output_file ✓${NC}"
}
