#!/usr/bin/env bash
set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKFLOWS_DIR="$REPO_DIR/workflows"

GREEN='\033[0;32m'
NC='\033[0m'

install_project() {
  local project_path="${1:-.}"
  local output_file="$project_path/AGENTS.md"

  echo ""
  echo "Generating AGENTS.md for Codex..."

  {
    echo "# 100x Dev Workflows"
    echo "# Generated by 100x-dev (https://github.com/rajitsaha/100x-dev)"
    echo "# Regenerate: run install.sh or adapters/codex.sh <project-path>"
    echo ""

    for f in gate test commit push launch lint security docs issue architect cloud-security enterprise-design db; do
      if [ -f "$WORKFLOWS_DIR/$f.md" ]; then
        echo "---"
        echo ""
        cat "$WORKFLOWS_DIR/$f.md"
        echo ""
      fi
    done
  } > "$output_file"

  echo -e "  ${GREEN}→ Generated $output_file ✓${NC}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_project "${1:-.}"
fi
